### ISSUE TITLE
Incompatibility with harmony-reflect

### ISSUE THREAD

**Issue by timkelty** [jscs-dev/gulp-jscs#100]
I haven't yet been able to determine with what package the problem lies ([harmony-reflect](https://github.com/tvcutsem/harmony-reflect), [jscs](https://github.com/jscs-dev/node-jscs), or gulp-jscs)...but I'm starting here!

Long story short - an update to [favicons](https://github.com/haydenbleasel/favicons) included the requiring of [harmony-reflect](https://github.com/tvcutsem/harmony-reflect). With that, when I ran my gulp tasksI started getting this error: 

```bash
❯ gulp lint:js
[23:39:09] Using gulpfile ~/Repos/fusionary-fed/templates/gulpfile.js
[23:39:09] Starting 'lint:js'...
[23:39:10] 'lint:js' errored after 165 ms
[23:39:10] TypeError: Object prototype may only be an Object or null: true
    at setPrototypeOf (native)
    at Function.Object.setPrototypeOf (/Users/timkelty/Repos/fusionary-fed/templates/node_modules/harmony-reflect/reflect.js:1655:14)
    at Object.prim_defineProperty.set (/Users/timkelty/Repos/fusionary-fed/templates/node_modules/harmony-reflect/reflect.js:1634:21)
    at Object.module.exports.configure (/Users/timkelty/Repos/fusionary-fed/templates/node_modules/jscs/lib/rules/disallow-dangling-underscores.js:88:51)
    at NodeConfiguration.<anonymous> (/Users/timkelty/Repos/fusionary-fed/templates/node_modules/jscs/lib/config/configuration.js:847:14)
    at Array.forEach (native)
    at NodeConfiguration.Configuration._useRules (/Users/timkelty/Repos/fusionary-fed/templates/node_modules/jscs/lib/config/configuration.js:845:37)
    at NodeConfiguration.Configuration.load (/Users/timkelty/Repos/fusionary-fed/templates/node_modules/jscs/lib/config/configuration.js:241:10)
    at StringChecker.configure (/Users/timkelty/Repos/fusionary-fed/templates/node_modules/jscs/lib/string-checker.js:67:29)
    at Checker.configure (/Users/timkelty/Repos/fusionary-fed/templates/node_modules/jscs/lib/checker.js:28:39)
```

I boiled it down to the simplest `gulpfile.js` I could that still threw the error:
```
var path    = require('path');
var gulp    = require('gulp');
var jscs    = require('gulp-jscs');
var Reflect  = require('harmony-reflect');

gulp.task('lint:js', function() {
  return gulp.src([
    path.join(process.cwd(), 'app/assets/js/**/*.js'),
  ])
  .pipe(jscs());
});
```

If I remove `require('harmony-reflect')`, no error.

I tried just running a similar node script with just `jscs`, but was not able to trigger the error, which is why I'm starting with an issue here.

Any ideas?

**Comment by timkelty** [comment]
Finally was able to reproduce this w/o Gulp, so I'll close this issue.
