### ISSUE TITLE
TypeError: Object.keys called on non-object

### ISSUE THREAD

**Issue by marcocalta** [jscs-dev/gulp-jscs#74]
I get this error when I run gulp. What I'm doing wrong? Can you help me to fix it? Thanks!

```
C:\xampp\htdocs\test>gulp
[10:54:45] Using gulpfile C:\xampp\htdocs\test\gulpfile.js
[10:54:45] Starting 'jscs'...
[10:54:45] 'jscs' errored after 54 ms
[10:54:45] TypeError: Object.keys called on non-object
    at Function.keys (native)
    at NodeConfiguration.Configuration._throwNonCamelCaseErrorIfNeeded (C:\xampp
\htdocs\test\node_modules\gulp-jscs\node_modules\jscs\lib\config\configuration.j
s:461:12)
    at NodeConfiguration.Configuration.load (C:\xampp\htdocs\test\node_modules\g
ulp-jscs\node_modules\jscs\lib\config\configuration.js:52:10)
    at StringChecker.configure (C:\xampp\htdocs\test\node_modules\gulp-jscs\node
_modules\jscs\lib\string-checker.js:66:29)
    at Checker.configure (C:\xampp\htdocs\test\node_modules\gulp-jscs\node_modul
es\jscs\lib\checker.js:26:39)
    at module.exports (C:\xampp\htdocs\test\node_modules\gulp-jscs\index.js:31:1
1)
    at Gulp.<anonymous> (C:\xampp\htdocs\test\gulpfile.js:46:15)
    at module.exports (C:\xampp\htdocs\test\node_modules\gulp\node_modules\orche
strator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\xampp\htdocs\test\node_modules\gulp\node_m
odules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\xampp\htdocs\test\node_modules\gulp\node_m
odules\orchestrator\index.js:214:10)
```

Gulpfile.js:

```
'use strict';

// Include gulp
var gulp = require('gulp');

// Include Plugins
var jshint = require('gulp-jshint');
var uglify = require('gulp-uglify');
var concat = require('gulp-concat');
var rename = require('gulp-rename');
var less = require('gulp-less');
var path = require('path');
var browserSync = require('browser-sync');
var reload      = browserSync.reload;
var jscs = require('gulp-jscs');
var noop = function () {};
var stylish = require('gulp-jscs-stylish');

// Less to Css
gulp.task('less', function () {
    return gulp.src('src/less/styles.less')
        .pipe(less())
        .pipe(gulp.dest('dist/css'));
});

// Lint Task
gulp.task('lint', function() {
    return gulp.src('src/js/*.js')
        .pipe(jshint())
        .pipe(jshint.reporter('default'));
});

// Concatenate & Minify JS
gulp.task('scripts', function () {
    return gulp.src('src/js/*.js')
        .pipe(concat('all.js'))
        .pipe(gulp.dest('dist'))
        .pipe(rename('all.min.js'))
        .pipe(uglify())
        .pipe(gulp.dest('dist'));
});

// Check JS code style
gulp.task('jscs', function () {
    gulp.src(['src/js/*.js'])
        .pipe(jscs())      // enforce style guide 
        .on('error', noop) // don't stop on error 
        .pipe(stylish());  // log style errors 
});

// Watch Files For Changes
gulp.task('watch', function () {


    // local
    browserSync({
        proxy: "localhost/test/"
    });

    gulp.watch('src/js/*.js', ['jscs', 'lint', 'scripts']);
    gulp.watch('src/less/*.less', ['less']);
    gulp.watch(['src/less/*.less', '*.htm']).on('change', reload);

});

// Default Task
gulp.task('default', ['jscs', 'lint', 'scripts', 'watch']);

```

depencies in package.json:
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "gulp": "^3.8.11",
    "bootstrap": "^3.3.4",
    "jquery": "^2.1.3"
  },
  "devDependencies": {
    "browser-sync": "^2.3.1",
    "gulp": "^3.8.11",
    "gulp-concat": "^2.2.0",
    "gulp-jscs": "^1.4.0",
    "gulp-jscs-stylish": "^1.0.2",
    "gulp-jshint": "^1.9.4",
    "gulp-less": "^3.0.1",
    "gulp-rename": "^1.2.0",
    "uglify": "^0.1.1"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

**Comment by jbdutton** [comment]
I believe this is because you did not pass in an options object to `jscs()`. #77 will improve this error message. I haven't been able to get glup-jscs to work yet myself I can't offer you any more advice, sorry.
