### ISSUE TITLE
StringChecker TypeError: _createConfiguration undefined

### ISSUE THREAD

**Issue by pixelshaded** [jscs-dev/gulp-jscs#85]
```
"gulp-jscs": "^1.6.0"
```
```
TypeError: undefined is not a function
    at StringChecker (node_modules\jscs\lib\string-checker.js:26:32)
    at Checker (node_modules\jscs\lib\checker.js:15:19)
    at Gulp.<anonymous> (gulp\jscs.js:17:10)
    at module.exports (node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at process._tickCallback (node.js:355:11)
    at Module.runMain [as _onTimeout] (module.js:503:11)
```

Running a simple gulp task:
```
gulp.task('testjscs', function(callback){
	return gulp.src('./src/precompile/js/**/*.js')
		.pipe(jscs());
});
```

Running grunt version of jscs task works fine.

**Comment by pixelshaded** [comment]
I've essentially copied the code from index.js in to my task file while installing needed deps with npm. I no longer get the TypeError which might indicate an issue with outdated dependencies for this module.

**Comment by jhubsharp** [comment]
I'm seeing this same stack error when running on NPM 3. This is running version 2.7.0 underneath gulp-jscs version 3.0.2. Going to attempt rebuilding the dependency tree and go from there.
